### ISSUE TITLE
🛣Unrealistic 

### ISSUE THREAD

**Issue by Fripe070** [TechnoShip123/TGoT#11]
I have noticed that the world is just a road with a textured sphere around, his to me seems slightly unrealistic and I think the the cause of this may be that in the real world raids for on much farther then they do in the game and the fact that as far as I know there aren’t any raids floating over the empty void.
I suggest adding a large plane underneath the road to act as some sort of ground and making the road go farther.

**Comment by TechnoShip123** [comment]
I'll plan to make the road bigger + add more obstacles, was focusing one more technical issues before.

**Comment by Fripe070** [comment]
Ok

**Comment by Dog-gamer124** [comment]
e
