### ISSUE TITLE
🚗Turning feels slow

### ISSUE THREAD

**Issue by Fripe070** [TechnoShip123/TGoT#12]
As the title says, the turning feels slow. 

I think the turning of the car would benefit from adding turning velocity so that the longer you hold down the turn button the faster it will turn (this might already be implemented but it’s still to slow).

This is probably a bad suggestion for how to fix the issue and there are probably many other better ways to do this

**Comment by TechnoShip123** [comment]
Purposeful for now, planning to add some things that won't benefit from a faster turn speed but I won't completely ditch this suggestion, may reopen.

**Comment by TechnoShip123** [comment]
Resolved, keep in mind that the new value decision was not taken lightly. I did some testing, felt that anything near 60 would be too high, and made the decision to raise it up to 55.
