### ISSUE TITLE
⬇️Driving backwards is a pain.

### ISSUE THREAD

**Issue by Fripe070** [TechnoShip123/TGoT#13]
Since the camera always stays in the same rotation when you turn around so you face the camera you can’t see where you are going.

**Comment by TechnoShip123** [comment]
Planning to fix this, will notify when I get started

**Comment by TechnoShip123** [comment]
Working on this right now in TGoT/dev

**Comment by TechnoShip123** [comment]
Resolved! Will appear in the master branch and new release when I open a PR along with commits that fix other issues.
