### ISSUE TITLE
Unrealistic cones

### ISSUE THREAD

**Issue by Dog-gamer124** [TechnoShip123/TGoT#18]
If you ram into a cone hard enough, your car will clip through the cone. This is unrealistic as normally the cone would 
a) Be pushed
b) Be squished
Also cones seem to teleport if you try to ram into them, again this is unrealistic as they would be pushed normally

https://user-images.githubusercontent.com/81295020/119817465-a644bc00-bf0b-11eb-9a13-35ad126e3a66.mp4

**Comment by TechnoShip123** [comment]
Sorry, won't be possible for now, although it might be achieved later on through other means. I don't want to increase the time spent for physics because can also reduce the performance of the game overall.
