### ISSUE TITLE
Mirror doesn't break off

### ISSUE THREAD

**Issue by SmallPepperZ** [TechnoShip123/TGoT#22]
Hello again,
I was recently playing this wonderful game on the v0.0.7 release, and I noticed a slight problem. If you are driving calmly down the road, but then see the traffic cones and swerve to avoid them like a good citizen, you can fall off the road. This is not the issue I'm addressing here, that is already well documented. The issue I'm reporting today is that when the car drives on its side (Figure 1) after using complicated driving maneuvers to get back onto the road, the mirror, which is scraping against the road, does not break off. This is clearly abhorrently unrealistic, and should be remedied immediately

---
https://user-images.githubusercontent.com/69822582/119859755-84771500-beca-11eb-81c5-b9e9d7f7b6f4.mov

**Comment by TechnoShip123** [comment]
As much as I would like to add this, it's a bit advanced for me. **However**, I am currently planning to create my own assets from scratch, which would allow me to do much more such as the realistic boxes from issue #10. I'll be marking this as closed for now, but _I still may add it_ ~~assuming I can survive making my own textures~~.
