### ISSUE TITLE
🎨 Customize Car Asset

### ISSUE THREAD

**Issue by TechnoShip123** [TechnoShip123/TGoT#23]
I'm planning to customize the asset for the car, in a way that will hopefully be able to resolve #22 and resolve #10

**Comment by TechnoShip123** [comment]
Update on the asset creation, I seem to be making progress.

**Comment by TechnoShip123** [comment]
Or not...



![image](https://user-images.githubusercontent.com/75491816/119885365-5cea7180-bef7-11eb-8f69-ab75f0e1bf36.png)

**Comment by TechnoShip123** [comment]
Made progress! The image below is from commit e5970d9!


![image](https://user-images.githubusercontent.com/75491816/119888450-fbc49d00-befa-11eb-831e-f696857ea8b8.png)

**Comment by TechnoShip123** [comment]
Car asset is fine, but the mesh needs to be adjusted now so that objects can settle down in the back.

**Comment by Fripe070** [comment]
That’s not a skipper car 😳
