### ISSUE TITLE
You can drive off the front and back, also physics or something

### ISSUE THREAD

**Issue by SmallPepperZ** [TechnoShip123/TGoT#7]
I was trying to have a nice driving experience, down the nice road, looking at the nice mountains, avoiding the traffic cones, when suddenly, I was falling. This road failed to implement as much as a warning sign. There needs to be something to prevent innocent drivers like myself from falling off of this road. If you do not add safety precautions, I will sue for negligence

**Comment by SmallPepperZ** [comment]
Demonstration of bug
![Picture of free-fall](https://user-images.githubusercontent.com/69822582/119750669-a5018980-be4e-11eb-8a34-57307b59469f.png)


[Video demonstration of unsafe road](https://user-images.githubusercontent.com/69822582/119750739-c1052b00-be4e-11eb-8bb9-07bbe5520881.mov)

**Comment by TechnoShip123** [comment]
Intentional lol, but I'll add try and add a sign.

**Comment by TechnoShip123** [comment]
Added warning signs to the end!
