### ISSUE TITLE
Texture breaks below road

### ISSUE THREAD

**Issue by SmallPepperZ** [TechnoShip123/TGoT#8]
In my attempt to document #7, I drove my car to the edge of the road. To demonstrate the issue, I continued keeping my foot on the gas pedal at the edge of the road, and drove off the edge. I then proceeded to upload that video to #7, and never closed the application. A few minutes later, the car is still falling, but I was shocked to see that it was no longer falling peacefully. You see, as the car fell, its materials rubberized, and the car became a JelloCar™. Unfortunately, this was no ordinary JelloCar™, it was a JelloCar™ with a strange texture, which was very disappointing to me, as I could no longer enjoy the beautiful serenity of a wobbly car falling through space. I request that this bug be fixed as soon as possible, so that I may  enjoy the beautiful serenity of a wobbly car falling through space. This texture bug ruins the JelloCarGazing experience.

https://user-images.githubusercontent.com/69822582/119751577-46d5a600-be50-11eb-9309-3ef00d86fd9a.mov

**Comment by TechnoShip123** [comment]
Interesting, I never noticed this lol. I'll start working on it in the Dev branch right now.

**Comment by TechnoShip123** [comment]
🆗 Steps taken to reproduce the issue were successful, I think I have an idea to fix this.


![temp](https://user-images.githubusercontent.com/75491816/119753769-f0bf2d80-be64-11eb-9284-71cebdcbafe4.gif)

**Comment by TechnoShip123** [comment]
Possible solution to the problem! You will now be brought back to safety from the JelloCar™ mess if you fall too far (see commit e531b12fecdbc7f593f27208ae7e1adb6686c130's message for more details). Currently awaiting workflow status for confirmation that the code is valid. ([https://github.com/TechnoShip123/TGoT/actions/runs/880602114](https://github.com/TechnoShip123/TGoT/actions/runs/880602114))

**Comment by TechnoShip123** [comment]
GitHub Actions succeeded, I'll do some final checks, await a 🛠 Unity Build Workflow status, then merge if it's good.
